import Image from "next/image";
import { CartDrawer } from "@/components/commerce/CartDrawer";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { getProduct } from "@/data/catalog";
import { BETWEEN_SIZES, MEASURING_NOTE, MEASURING_STEPS, SIZE_CHART } from "@/data/fit";
import { image } from "@/lib/image";

export default function SizeGuidePage() { const triangle = getProduct("sunchild-triangle-top")!; const fitImage = image(triangle.images[0]); return <><SiteHeader /><main className="guide-page"><div className="container"><header><p className="label accent">Find your Piura fit</p><h1 className="display display-lg">Made to feel<br /><em>like yours.</em></h1><p>Every Piura piece runs true to size. Measure once, then wear it everywhere.</p></header><section className="guide-fit-reference" aria-labelledby="fit-reference-title"><div className="guide-fit-image"><Image src={fitImage.src} alt="Sunchild Triangle Top on the body" width={fitImage.width} height={fitImage.height} sizes="(max-width: 900px) 100vw, 45vw" /><span className="label">Fit, before price</span></div><div className="guide-fit-copy"><p className="label accent">The Triangle</p><h2 id="fit-reference-title" className="display display-sm">See the fit<br /><em>first.</em></h2><dl><div><dt>Support</dt><dd>Sculpt and support</dd></div><div><dt>Adjustability</dt><dd>Adjustable ties</dd></div><div><dt>Coverage</dt><dd>Minimal / cheeky</dd></div><div><dt>Fit</dt><dd>True to size</dd></div></dl><p>Top and bottom sizes are chosen separately when you build a set.</p></div></section><section className="guide-table"><table><caption>Body measurements in inches</caption><thead><tr><th>Piura size</th><th>Bust</th><th>Waist</th><th>Hips</th></tr></thead><tbody>{SIZE_CHART.map((row) => <tr key={row.size}><th>{row.size}</th><td>{row.bust.join("–")}</td><td>{row.waist.join("–")}</td><td>{row.hips.join("–")}</td></tr>)}</tbody></table></section><p className="guide-note">{MEASURING_NOTE}</p><section className="guide-measure"><h2 className="display display-sm">How to measure.</h2><ol>{MEASURING_STEPS.map((step) => <li key={step.key}><span>{step.letter}</span><div><h3>{step.name}</h3><p>{step.how}</p></div></li>)}</ol></section><section className="guide-between"><p className="label accent">Between sizes?</p><p>{BETWEEN_SIZES}</p></section></div></main><SiteFooter /><CartDrawer /></>; }
