import Image from "next/image";
import { CartDrawer } from "@/components/commerce/CartDrawer";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { STORY_LONGFORM } from "@/data/site";
import { image } from "@/lib/image";

const storyFrames = [
  ["stills/boat-sunset-look-back.jpg", "A look back toward the water"],
  ["stills/boat-sunset-poster.jpg", "Piura at sunset"],
  ["stills/boat-sunset-profile.jpg", "Piura on the boat at sunset"],
] as const;

export default function StoryPage() { const hero = image("stills/boat-sunset-poster.jpg"); const miami = image("lifestyle/life-01.jpg"); const peru = image("lifestyle/life-68.jpg"); return <><SiteHeader overlay /><main><section className="story-hero"><Image src={hero.src} alt="Woman sitting on a boat at sunset" width={hero.width} height={hero.height} priority sizes="100vw" /><div /><div className="container"><p className="label">Our story</p><h1 className="display display-xl">Two coasts.<br /><em>One summer.</em></h1><div className="story-hero-reel" aria-label="Three photographic frames from Piura’s story">{storyFrames.map(([key, alt], index) => { const frame = image(key); return <figure key={key} className={`story-hero-frame story-hero-frame-${index + 1}`}><Image src={frame.src} alt={alt} width={frame.width} height={frame.height} sizes="(max-width: 620px) 31vw, 16vw" /><figcaption>0{index + 1}</figcaption></figure>; })}</div></div></section><section className="story-intro section"><div className="container"><p className="label accent">The beginning</p><p className="display display-md">The bikinis her grandmother brought from Peru felt like nothing she could find at home.</p></div></section><StoryChapter eyebrow="I · Miami" title="Practically raised in a bikini." lines={STORY_LONGFORM.miami} asset={miami} alt="Piura bikini at the coast" /><StoryChapter reversed eyebrow="II · Piura, Perú" title="The city of eternal heat." lines={STORY_LONGFORM.peru} asset={peru} alt="Piura by the water" /><section className="story-close on-dark"><div className="container"><p className="label accent">III · Now</p><h2 className="display display-lg">A celebration of<br /><em>where we come from.</em></h2><p>{STORY_LONGFORM.now[0]}</p><p>{STORY_LONGFORM.now[1]}</p></div></section></main><SiteFooter /><CartDrawer /></>; }
function StoryChapter({ eyebrow, title, lines, asset, alt, reversed = false }: { eyebrow: string; title: string; lines: readonly string[]; asset: ReturnType<typeof image>; alt: string; reversed?: boolean }) { return <section className={`story-chapter ${reversed ? "story-chapter-reversed" : ""}`}><div className="story-chapter-image"><Image src={asset.src} alt={alt} width={asset.width} height={asset.height} sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="story-chapter-copy"><p className="label accent">{eyebrow}</p><h2 className="display display-lg">{title}</h2>{lines.map((line) => <p key={line}>{line}</p>)}</div></section>; }
