// Generated by scripts/build-products.mjs from scripts/catalog.json. Do not edit by hand.
// Source: public product data on piuraswim.com (titles, prices, sizes, availability,
// descriptions, fit notes and fabric copy are verbatim from the storefront).

import type { ImageKey } from './image-manifest';

export type Size = 'S' | 'M' | 'L' | 'XL';
export type Category = 'tops' | 'bottoms';
export type CollectionKey = 'sunchild' | 'moonchild' | 'classics';

export type Product = {
  handle: string;
  title: string;
  price: number;
  category: Category;
  collection: CollectionKey;
  justDropped: boolean;
  pairsWith: string;
  sizes: Size[];
  available: Size[];
  images: ImageKey[];
  description: string;
  fitNotes: string[];
  fabric: string[];
};

export const PRODUCTS: Product[] = [
  {
    "handle": "sunchild-triangle-top",
    "title": "Sunchild Triangle Top",
    "price": 49,
    "category": "tops",
    "collection": "sunchild",
    "justDropped": true,
    "pairsWith": "sunchild-triangle-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/36775385-EF1D-4BDA-8879-440389DA4DA9.webp",
      "products/C6F4DE24-FB79-4617-843C-F85D1CB80541.webp",
      "products/D4CBCC8F-D4E4-48CA-AFCE-C79B6FFE8761.webp"
    ],
    "description": "The long-awaited addition to the Sunchild print. The signature Piura pattern you already love, reimagined in a fresh, flattering triangle cut, designed to sculpt and support while keeping that effortless beach-girl feel. Wear it under the sun, by the ocean, or wherever your summer takes you.",
    "fitNotes": [
      "Classic triangle silhouette with adjustable ties",
      "Signature Sunchild print",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "sunchild-triangle-bottom",
    "title": "Sunchild Triangle Bottom",
    "price": 49,
    "category": "bottoms",
    "collection": "sunchild",
    "justDropped": true,
    "pairsWith": "sunchild-triangle-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/D06AC86B-4E9A-4798-8522-1C710D5F5A1F.webp",
      "products/125BE315-34FB-463C-BD82-6429732A6A23.webp",
      "products/7F5C6C89-3853-45E1-A437-C64A4D5BAAC9.webp",
      "products/60175D54-F198-4046-B998-BBCADCA692AE.webp"
    ],
    "description": "The Sunchild print in a flattering triangle cut. Seamless and fully lined, with minimal, cheeky coverage for effortless tan lines. Pairs with the Sunchild Triangle Top.",
    "fitNotes": [
      "Minimal / cheeky coverage",
      "Seamless triangle silhouette",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "moonchild-triangle-top",
    "title": "Moonchild Triangle Top",
    "price": 49,
    "category": "tops",
    "collection": "moonchild",
    "justDropped": true,
    "pairsWith": "moonchild-triangle-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/6F82D216-4D22-4D33-AEE3-17B5E2433A67.webp",
      "products/E908E22C-F7B9-4875-BC5B-6D8AAC20F84B.webp",
      "products/C1820555-FA2F-4177-92C0-FF19E4E6F40A.webp"
    ],
    "description": "The long-awaited addition to the Moonchild print. The signature Piura pattern reimagined in a fresh, flattering triangle cut, designed to sculpt and support while keeping that effortless beach-girl feel. The perfect blend of statement and simplicity.",
    "fitNotes": [
      "Classic triangle silhouette with adjustable ties",
      "Signature Moonchild print",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "moonchild-triangle-bottom",
    "title": "Moonchild Triangle Bottom",
    "price": 49,
    "category": "bottoms",
    "collection": "moonchild",
    "justDropped": true,
    "pairsWith": "moonchild-triangle-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/2845632E-112F-4B1E-8BB9-D27BF02E9F23.webp",
      "products/1CB78A8B-46F7-42B2-AD8B-AE04A125A73F.webp",
      "products/C1820555-FA2F-4177-92C0-FF19E4E6F40A_2c1f4b56-d012-4127-9d6d-83d0056c6597.webp"
    ],
    "description": "The Moonchild print in a flattering triangle cut. Seamless and fully lined, with minimal, cheeky coverage made for long days by the water. Pairs with the Moonchild Triangle Top.",
    "fitNotes": [
      "Minimal / cheeky coverage",
      "Seamless triangle silhouette",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "moonchild-bottom",
    "title": "Moonchild Mesh Bottom",
    "price": 49,
    "category": "bottoms",
    "collection": "moonchild",
    "justDropped": false,
    "pairsWith": "moonchild-bandeau-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm290.webp",
      "products/PiuraEcomm245.webp",
      "products/PiuraEcomm275.webp",
      "products/IMG_1530.webp",
      "products/PiuraEcomm235.webp",
      "products/PiuraEcomm250.webp",
      "products/4.webp",
      "products/D0A069D5-49AC-4873-8176-D4FB329B60D0.webp"
    ],
    "description": "The Moonchild print with soft mesh detailing. A smooth, seamless bottom with cheeky coverage and a clean silhouette. Pairs with the Moonchild Bandeau Top.",
    "fitNotes": [
      "Cheeky coverage",
      "Soft mesh detailing",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "moonchild-bandeau-top",
    "title": "Moonchild Bandeau Top",
    "price": 49,
    "category": "tops",
    "collection": "moonchild",
    "justDropped": false,
    "pairsWith": "moonchild-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm240.webp",
      "products/PiuraEcomm235.webp",
      "products/PiuraEcomm250.webp",
      "products/PiuraEcomm245.webp",
      "products/PiuraEcomm287.webp",
      "products/BA1B24F3-1459-41ED-8423-CA904E115309.webp",
      "products/IMG_1701.webp",
      "products/IMG_1470.webp",
      "products/IMG_1530.webp",
      "products/IMG_1606.webp",
      "products/3.webp"
    ],
    "description": "Bandeau bikini top featuring the Moonchild print with soft mesh detailing. A strapless silhouette designed for a smooth, flattering fit, no padding, for a natural shape. Pairs with the Moonchild Mesh Bottom.",
    "fitNotes": [
      "Strapless bandeau silhouette",
      "No padding, for a natural fit",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "lotus-bottom",
    "title": "Sunchild Mesh Bottom",
    "price": 49,
    "category": "bottoms",
    "collection": "sunchild",
    "justDropped": false,
    "pairsWith": "sunchild-bandeau-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm677.webp",
      "products/PiuraEcomm621_e5728d89-9e57-400a-a810-b2ea86d3e8aa.webp",
      "products/PiuraEcomm655.webp",
      "products/PiuraEcomm609.webp",
      "products/IMG_1207.webp",
      "products/IMG_1004.webp",
      "products/IMG_1441.webp",
      "products/IMG_1006.webp",
      "products/4.webp"
    ],
    "description": "The Sunchild print with soft mesh detailing. A smooth, seamless bottom with cheeky coverage and a clean silhouette. Pairs with the Sunchild Bandeau Top.",
    "fitNotes": [
      "Cheeky coverage",
      "Soft mesh detailing",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "sunchild-bandeau-top",
    "title": "Sunchild Bandeau Top",
    "price": 49,
    "category": "tops",
    "collection": "sunchild",
    "justDropped": false,
    "pairsWith": "lotus-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm621.webp",
      "products/PiuraEcomm629.webp",
      "products/PiuraEcomm677.webp",
      "products/IMG_1441.webp",
      "products/CF0DF318-F94C-40A0-83F5-357C4E0B0931.webp",
      "products/D2BB7E74-0BDA-4C05-9D94-DD7D2AB566BB.webp",
      "products/3.webp"
    ],
    "description": "Bandeau bikini top featuring the Sunchild print with soft mesh detailing. A strapless silhouette designed for a smooth, flattering fit, no padding, for a natural shape. Pairs with the Sunchild Mesh Bottom.",
    "fitNotes": [
      "Strapless bandeau silhouette",
      "No padding, for a natural fit",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "bella-side-tie-scrunch-bottom",
    "title": "Bella Side-Tie Scrunch Bottom",
    "price": 42,
    "category": "bottoms",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "bella-bikini-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm99.webp",
      "products/IMG_9072_3_c5acd4ad-9d38-44f2-ac41-03e73e4d1a98.webp",
      "products/IMG_9015.webp",
      "products/DSC01031.webp",
      "products/DSC01010_3cca2cba-c53c-481f-ba60-e85f489d389d.webp",
      "products/pinkfront1_5cf865d7-7ecd-4c85-bf19-4cb0aba550db.webp",
      "products/2_2.webp"
    ],
    "description": "Side-tie bikini bottom with scrunch detail and contrasting ties. Minimal coverage and adjustable sides for a fit that is entirely yours. Pairs with the Bella Bikini Top.",
    "fitNotes": [
      "Minimal / cheeky coverage",
      "Adjustable side ties with scrunch-back detail",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "bella-bikini-top",
    "title": "Bella Bikini Top",
    "price": 42,
    "category": "tops",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "bella-side-tie-scrunch-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "L",
      "XL"
    ],
    "images": [
      "products/IMG_9015.webp",
      "products/PiuraEcomm112.webp",
      "products/IMG_9072_3_c5acd4ad-9d38-44f2-ac41-03e73e4d1a98.webp",
      "products/pinkfront.webp",
      "products/PiuraEcomm105_8d41b75f-695b-44fb-b745-f082d6c838d9.webp",
      "products/tempImagewuRDbJ.webp",
      "products/tempImage3KLZft.webp",
      "products/DSC00984.webp",
      "products/1_2.webp"
    ],
    "description": "Minimal triangle bikini top in soft baby pink with adjustable neck and back ties. Designed for a customizable, flattering fit and effortless support. Pairs with the Bella Side-Tie Scrunch Bottom.",
    "fitNotes": [
      "Classic triangle silhouette",
      "Adjustable neck and back ties",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "bali-side-tie-bikini-scrunch-bottom",
    "title": "Bali Side-Tie Bikini Scrunch Bottom",
    "price": 42,
    "category": "bottoms",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "bali-bikini-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm850.webp",
      "products/PiuraEcomm788.webp",
      "products/PiuraEcomm810.webp",
      "products/PiuraEcomm801.webp",
      "products/greenfront1.webp",
      "products/2_2.webp"
    ],
    "description": "Cheeky side-tie bikini bottom with scrunch detail and contrasting ties. Minimal coverage and adjustable sides for the perfect fit. Pairs with the Bali Bikini Top.",
    "fitNotes": [
      "Minimal / cheeky coverage",
      "Adjustable side ties with scrunch-back detail",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "bali-bikini-top",
    "title": "Bali Bikini Top",
    "price": 42,
    "category": "tops",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "bali-side-tie-bikini-scrunch-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm798.webp",
      "products/PiuraEcomm822.webp",
      "products/PiuraEcomm850.webp",
      "products/greenfront.webp",
      "products/DSCF1901.webp",
      "products/DSC00942_3537271f-1d6b-4a00-b8e5-817f2179ef03.webp",
      "products/1_2.webp"
    ],
    "description": "Minimal triangle bikini top with contrasting edges and adjustable neck and back ties. Designed for a customizable fit and effortless support. Pairs with the Bali Side-Tie Scrunch Bottom.",
    "fitNotes": [
      "Classic triangle silhouette",
      "Adjustable neck and back ties",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "sara-side-tie-scrunch-bottom",
    "title": "Sara Side-Tie Scrunch Bottom",
    "price": 42,
    "category": "bottoms",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "sara-bikini-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm750.webp",
      "products/PiuraEcomm698.webp",
      "products/PiuraEcomm778.webp",
      "products/DSCF2068.webp",
      "products/DSCF2067_3e1843d1-a129-4f8e-9df5-820867d307ce.webp",
      "products/yellowback.webp",
      "products/yellowfront1_93ae48be-93b3-412f-b0f2-28671afab5fb.webp",
      "products/2_2.webp"
    ],
    "description": "Minimal bikini bottom designed for a flattering, comfortable fit. A clean silhouette with cheeky coverage for effortless tan lines. Pairs with the Sara Bikini Top.",
    "fitNotes": [
      "Cheeky coverage for effortless tan lines",
      "Clean, seamless silhouette",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "sara-bikini-top",
    "title": "Sara Bikini Top",
    "price": 42,
    "category": "tops",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "sara-side-tie-scrunch-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm688.webp",
      "products/PiuraEcomm778.webp",
      "products/PiuraEcomm725.webp",
      "products/yellowfront-3_6f11b801-b3ce-4e50-8c2d-acd5e3eb9a04.webp",
      "products/DSCF2025.webp",
      "products/DSCF2067.webp",
      "products/1_2.webp"
    ],
    "description": "Minimal bikini top designed for a clean, flattering fit. Adjustable straps allow for a customizable, comfortable feel. Pairs with the Sara Side-Tie Scrunch Bottom.",
    "fitNotes": [
      "Minimal silhouette with adjustable straps",
      "Seamless, hardware-free design",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "marina-tri-bandeau-bottom",
    "title": "Marina Tri Bandeau Bottom",
    "price": 49,
    "category": "bottoms",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "marina-tri-bandeau-top",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm214.webp",
      "products/PiuraEcomm145.webp",
      "products/PiuraEcomm171.webp",
      "products/czM6Ly9tZWRpYS1wcml2YXRlLmNhbnZhLmNvbS9QV2xxOC9NQUZfOTFQV2xxOC8xL3AucG5n_1.webp",
      "products/PiuraEcomm206.webp",
      "products/PiuraEcomm208.webp",
      "products/4.webp"
    ],
    "description": "Bikini bottom featuring a flattering V-cut silhouette with breathable mesh detailing. Designed to elongate the legs while offering comfortable, cheeky coverage. Pairs with the Marina Tri Bandeau Top.",
    "fitNotes": [
      "V-cut waist silhouette, designed to elongate",
      "Cheeky coverage with mesh detailing",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with a soft, sculpting stretch",
      "Fully lined, seamless construction, no hardware against the skin",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  },
  {
    "handle": "marina-tri-bandeau-top",
    "title": "Marina Tri Bandeau Top",
    "price": 49,
    "category": "tops",
    "collection": "classics",
    "justDropped": false,
    "pairsWith": "marina-tri-bandeau-bottom",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "available": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "images": [
      "products/PiuraEcomm148.webp",
      "products/PiuraEcomm186.webp",
      "products/PiuraEcomm214.webp",
      "products/PiuraEcomm171.webp",
      "products/czM6Ly9tZWRpYS1wcml2YXRlLmNhbnZhLmNvbS9QV2xxOC9NQUZfOTFQV2xxOC8xL3AucG5n.webp",
      "products/IMG_1909_0c6e6002-0c4f-4566-b7c6-c3115f6f74a9.webp",
      "products/3.webp"
    ],
    "description": "A curved bandeau top designed to accentuate and flatter, with breathable mesh detailing and discreet side support for lift and shape. Pairs with the Marina Tri Bandeau Bottom.",
    "fitNotes": [
      "Curved bandeau silhouette with side support",
      "Breathable mesh cutout detailing",
      "Model wears size Small, fits true to size"
    ],
    "fabric": [
      "Luxury nylon / spandex blend with breathable mesh detailing",
      "Side support engineered for lift, shape, and stability",
      "Fully lined, pull-on seamless construction",
      "Hand wash cold, lay flat to dry in the shade"
    ]
  }
];
